name: rekognition
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pipreqs
  - pip:
      - icecream==2.1.2
      - boto3==1.21.32
      - Pillow==9.1.0
      - pytest==7.1.1
      - boto3==1.21.32
      - botocore==1.24.33
      - Flask==2.1.1
